In [1]:
import numpy as np
import pandas as pd
import os, glob
pd.options.display.float_format = '{:0.2f}'.format

In [2]:
# @TODO: Change hard-coded paths to wildcards
transfus_yes_rank = pd.read_csv('/MFMDatasets/MFM_bopf/data/csl/Final_cohort_rank-transfus_yes-Cramer.csv', index_col=0)
trans_loss_rank = pd.read_csv('/MFMDatasets/MFM_bopf/data/csl/Final_cohort_rank-trans_loss-Cramer.csv', index_col=0)
trans_hyster_rank = pd.read_csv('/MFMDatasets/MFM_bopf/data/csl/Final_cohort_rank-transfus_hyster-Cramer.csv', index_col=0)
hysterectomy_rank = pd.read_csv('/MFMDatasets/MFM_bopf/data/csl/Final_cohort_rank-Hysterectomy-Cramer.csv', index_col=0)

# No longer used
#t_all_rank = pd.read_csv('/MFMDatasets/MFM_bopf/data/csl/Final_cohort_rank-transfus_all-Cramer.csv', index_col=0)

In [3]:
transfus_yes_rank.head(200)

                Host_C  Ins_C  Age_C  race_C  RAND_C  mean_rank
Inoxy_incrdose       2      2      2       2       2       1.00
Intratocolytix       5      3      3       3       3       2.00
Admcontract          3      6      4       5       4       3.00
Education            6      4      5       4       5       4.00
HosEpiNurse          4      7      8       7       8       5.50
...                ...    ...    ...     ...     ...        ...
other_TD           194    204    181     194     202     196.00
version9           221    208    179     191     177     197.00
AB_clind           221    198    171     205     182     198.00
Ind_Vbleed         178    196    226     192     187     199.00
Hxheartdis         167    201    199     211     218     201.00

[200 rows x 6 columns]

In [4]:
combined = pd.DataFrame(transfus_yes_rank['mean_rank'].rank().astype('int')).rename(columns={'mean_rank':"transfus_yes"})
combined

                transfus_yes
Inoxy_incrdose             1
Intratocolytix             2
Admcontract                3
Education                  4
HosEpiNurse                5
...                      ...
Hyp_othr                 222
Ind_Chorio               222
Hyp_ace                  222
Hyp_alpha                222
R_preg                   222

[227 rows x 1 columns]

In [5]:
next_df = pd.DataFrame(trans_hyster_rank['mean_rank'].rank().astype('int'))
combined = pd.merge(combined, next_df, left_index=True, right_index=True)
combined.rename(columns={'mean_rank':"trans_hyster"}, inplace=True)
combined

                transfus_yes  trans_hyster
Inoxy_incrdose             1             1
Intratocolytix             2             2
Admcontract                3             3
Education                  4             4
HosEpiNurse                5             5
...                      ...           ...
Hyp_othr                 222           222
Ind_Chorio               222           216
Hyp_ace                  222           222
Hyp_alpha                222           222
R_preg                   222           222

[226 rows x 2 columns]

In [6]:
next_df = pd.DataFrame(trans_loss_rank['mean_rank'].rank().astype('int'))
combined = pd.merge(combined, next_df, left_index=True, right_index=True)
combined.rename(columns={'mean_rank':"trans_loss"}, inplace=True)
combined

                transfus_yes  trans_hyster  trans_loss
Inoxy_incrdose             1             1           7
Intratocolytix             2             2          26
Admcontract                3             3           8
Education                  4             4          20
HosEpiNurse                5             5          18
...                      ...           ...         ...
Hyp_othr                 222           222         224
Ind_Chorio               222           216         213
Hyp_ace                  222           222         224
Hyp_alpha                222           222         224
R_preg                   222           222         224

[226 rows x 3 columns]

In [7]:
next_df = pd.DataFrame(hysterectomy_rank['mean_rank'].rank().astype('int'))
combined = pd.merge(combined, next_df, left_index=True, right_index=True)
combined.rename(columns={'mean_rank':"Hysterectomy"}, inplace=True)
combined

                transfus_yes  trans_hyster  trans_loss  Hysterectomy
Inoxy_incrdose             1             1           7            20
Intratocolytix             2             2          26           108
Admcontract                3             3           8            35
Education                  4             4          20           116
HosEpiNurse                5             5          18            50
...                      ...           ...         ...           ...
Hyp_othr                 222           222         224           189
Ind_Chorio               222           216         213           189
Hyp_ace                  222           222         224           189
Hyp_alpha                222           222         224           189
R_preg                   222           222         224           189

[226 rows x 4 columns]

In [8]:
# Add column for the average rank and sort by it
combined['mean_rank'] = combined.apply(np.average, axis=1)
#combined['mean_rank'] = combined.apply(np.average, axis=1).rank().astype('int')
combined.sort_values(by='mean_rank', ascending=True, inplace=True)
combined.head(50)

,transfus_yes,trans_hyster,trans_loss,Hysterectomy,mean_rank
Inoxy_incrdose,1,1,7,20,7.25
HxnumCS,13,15,3,10,10.25
BESTGA,8,8,9,18,10.75
Admcontract,3,3,8,35,12.25
Dilat_lst,16,16,4,13,12.25
ROMmeth,18,18,5,16,14.25
Augment,11,10,33,19,18.25
HospElectCS,5,6,35,28,18.50
Admpresent,15,12,11,36,18.50
HosEpiNurse,5,5,18,50,19.50
Admefface,25,25,21,12,20.75
Delmode,46,44,1,2,23.25
ga,26,26,31,13,24.00
Episiotomy,19,19,23,41,25.50
Delfetalpos,12,13,53,25,25.75
DMControl,7,7,22,69,26.25
Admreason,20,21,50,21,28.00
AdmBishop,9,9,41,56,28.75
AdmSBP,10,11,13,82,29.00
previa9,38,36,36,8,29.50
AdmDBP,13,14,16,77,30.00
previa_chart,43,38,38,4,30.75
Anteanemia,31,31,38,25,31.25
Anteprevia,44,41,42,4,32.75
abruption,29,28,30,45,33.00
TrialLabor,70,60,5,1,34.00
Admconsistency,21,22,65,30,34.50
Intratocolytix,2,2,26,108,34.50
Antesteroid,27,27,52,34,35.00
delivery,69,66,2,3,35.00
Admcervpos,23,23,70,27,35.75
Education,4,4,20,116,36.00
IntraMgSO,35,35,43,37,37.50
HospElectInd,17,17,75,57,41.50
MomICU,36,40,76,15,41.75
Presentdel,50,49,28,43,42.50
Postfever,54,51,27,38,42.50
CS_Pprevia,55,47,45,24,42.75
Intraabrupt,34,32,55,53,43.50
Ind_Unkn,21,20,32,122,48.75
Anteabruption,38,37,48,76,49.75
AB_ceph,48,48,63,40,49.75
Hxcsection,88,84,18,9,49.75
Accrete,65,51,80,11,51.75
MthInd_AROM,24,24,77,86,52.75
uscar,106,94,14,6,55.00
Marital,33,33,99,60,56.25
vertex,83,78,37,31,57.25
Antebleed3,59,58,82,33,58.00
ThreatenedPB,41,45,93,55,58.50

In [9]:
# NOTE - saving this in /MFMDatasets instead of /slurm_storage
filename = '/MFMDatasets/MFM_bopf/data/csl/Final_Dataset_rank-Cramer.csv'
if not os.path.exists(filename):
    combined.to_csv(filename)

In [10]:
#combined.drop('mean', axis=1, inplace=True)
combined.drop('mean_rank', axis=1, inplace=True)
combined.head()

                transfus_yes  trans_hyster  trans_loss  Hysterectomy
Inoxy_incrdose             1             1           7            20
HxnumCS                   13            15           3            10
BESTGA                     8             8           9            18
Admcontract                3             3           8            35
Dilat_lst                 16            16           4            13

In [11]:
# Recalc average without Hysterectomy
combined['mean3'] = combined[['transfus_yes','trans_hyster','trans_loss']].apply(np.average, axis=1)
#combined['mean_rank'] = combined.apply(np.average, axis=1).rank().astype('int')
#combined.sort_values(by='mean_rank', ascending=True, inplace=True)
combined.sort_values(by='mean3', ascending=True, inplace=True)
combined.head(50)

                transfus_yes  trans_hyster  trans_loss  Hysterectomy  mean3
Inoxy_incrdose             1             1           7            20   3.00
Admcontract                3             3           8            35   4.67
BESTGA                     8             8           9            18   8.33
Education                  4             4          20           116   9.33
HosEpiNurse                5             5          18            50   9.33
Intratocolytix             2             2          26           108  10.00
HxnumCS                   13            15           3            10  10.33
AdmSBP                    10            11          13            82  11.33
Dilat_lst                 16            16           4            13  12.00
DMControl                  7             7          22            69  12.00
Admpresent                15            12          11            36  12.67
ROMmeth                   18            18           5            16  13.67
AdmDBP                    13            14          16            77  14.33
HospElectCS                5             6          35            28  15.33
Augment                   11            10          33            19  18.00
AdmBishop                  9             9          41            56  19.67
Episiotomy                19            19          23            41  20.33
Admefface                 25            25          21            12  23.67
Ind_Unkn                  21            20          32           122  24.33
Delfetalpos               12            13          53            25  26.00
ga                        26            26          31            13  27.67
abruption                 29            28          30            45  29.00
Admreason                 20            21          50            21  30.33
Delmode                   46            44           1             2  30.33
Anteanemia                31            31          38            25  33.33
Antesteroid               27            27          52            34  35.33
Admconsistency            21            22          65            30  36.00
HospElectInd              17            17          75            57  36.33
previa9                   38            36          36             8  36.67
IntraMgSO                 35            35          43            37  37.67
Admcervpos                23            23          70            27  38.67
previa_chart              43            38          38             4  39.67
Intraabrupt               34            32          55            53  40.33
Anteabruption             38            37          48            76  41.00
MthInd_AROM               24            24          77            86  41.67
Anteprevia                44            41          42             4  42.33
Presentdel                50            49          28            43  42.33
Postfever                 54            51          27            38  44.00
abruptio9                 40            43          49           119  44.00
TrialLabor                70            60           5             1  45.00
delivery                  69            66           2             3  45.67
Operative                 37            39          71            97  49.00
CS_Pprevia                55            47          45            24  49.00
MomICU                    36            40          76            15  50.67
AB_ceph                   48            48          63            40  53.00
Marital                   33            33          99            60  55.00
Endometritis              58            56          60           189  58.00
Lac_Unkn                  75            72          29           135  58.67
Meconium                  42            42          92            87  58.67
ThreatenedPB              41            45          93            55  59.67

In [12]:
# NOTE - saving this in /MFMDatasets instead of /slurm_storage
filename = '/MFMDatasets/MFM_bopf/data/csl/Final_Dataset_mean3_rank-Cramer.csv'
if not os.path.exists(filename):
    combined.to_csv(filename)