In [1]:
import pandas as pd
import numpy as np
import os
import glob
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
%config Completer.use_jedi = False
pd.options.display.float_format = '{:,.4f}'.format

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
df_he = pd.read_csv('SiteCompareData.csv', header=0, index_col=0, delimiter='\t')
df_he

,All_Sites,41,42,43,44,45,46,48,49,50,51,52
Stat,,,,,,,,,,,,
MCC,0.3175,0.2265,0.3522,0.3559,0.2869,0.3421,0.3019,0.1293,0.3190,0.3707,0.0950,0.3678
ROC,0.8929,0.8702,0.8744,0.8785,0.8361,0.8703,0.8834,0.7946,0.8729,0.8942,0.7418,0.8549
F2,0.4568,0.3125,0.5078,0.5227,0.4505,0.5037,0.4173,0.1672,0.4775,0.5421,0.1033,0.5604
PR_AUC,0.2675,0.1604,0.2405,0.2726,0.2806,0.2114,0.1710,0.0633,0.2380,0.3469,0.0245,0.2489

In [5]:
df_he_inv = df_he.T
df_he_inv

Stat         MCC    ROC     F2  PR_AUC
All_Sites 0.3175 0.8929 0.4568  0.2675
41        0.2265 0.8702 0.3125  0.1604
42        0.3522 0.8744 0.5078  0.2405
43        0.3559 0.8785 0.5227  0.2726
44        0.2869 0.8361 0.4505  0.2806
45        0.3421 0.8703 0.5037  0.2114
46        0.3019 0.8834 0.4173  0.1710
48        0.1293 0.7946 0.1672  0.0633
49        0.3190 0.8729 0.4775  0.2380
50        0.3707 0.8942 0.5421  0.3469
51        0.0950 0.7418 0.1033  0.0245
52        0.3678 0.8549 0.5604  0.2489

In [9]:
#fig = plt.figure()
#num_labels = 25
#ax = df_he_inv.iloc[0:num_labels,:].plot(figsize=(12,5), title="EBLoss by Site")
#ax.set_ylabel("Value")
#ax.set_xlabel("Sitenum")
#plt.draw()
#plt.show()