In [1]:
import sys
import os
import numpy as np
import pandas as pd
%matplotlib inline

In [2]:
#pd.options.display.max_columns = None
#pd.options.display.float_format = '{:,.2f}'.format
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
%config Completer.use_jedi = False

# Read in original dataset

In [3]:
%%time
csl_df = pd.read_sas('/MFMDatasets/MFM_bopf/data/csl/csllinkedbypreg.sas7bdat', format = 'sas7bdat', encoding='iso-8859-1')
csl_df.head()

CPU times: user 20 s, sys: 9.26 s, total: 29.2 s
Wall time: 32.7 s

,Sitenum,MomID,Marital,Education,Insurance,Momage,Parity,Gravidity,Hxlivebirth,Hxmacrosomia,...,Fulldilattime,Placenttime,Inducttime,Ripentime,ROMtime,Epiduraltime,Intraantibtime,USdays,LMPdays,onepregflag
0,41,41-00001,1.0,3.0,1.0,34.0,4.0,5.0,4.0,1.0,...,15.0,4.0,361.0,NaN,300.0,343.0,346.0,103.0,271.0,2.0
1,41,41-00001,1.0,3.0,1.0,36.0,5.0,6.0,5.0,2.0,...,18.0,3.0,369.0,NaN,251.0,314.0,NaN,128.0,278.0,2.0
2,41,41-00002,1.0,3.0,1.0,37.0,1.0,3.0,1.0,1.0,...,NaN,1.0,NaN,NaN,1.0,4.0,NaN,128.0,268.0,1.0
3,41,41-00003,1.0,3.0,1.0,36.0,1.0,4.0,1.0,1.0,...,69.0,4.0,382.0,NaN,369.0,364.0,NaN,133.0,273.0,1.0
4,41,41-00004,1.0,2.0,1.0,34.0,2.0,6.0,2.0,1.0,...,12.0,5.0,339.0,NaN,105.0,116.0,455.0,204.0,274.0,1.0

In [4]:
csl_df.set_index('MomID', inplace=True)
csl_df

,Sitenum,Marital,Education,Insurance,Momage,Parity,Gravidity,Hxlivebirth,Hxmacrosomia,Hxpreterm,...,Fulldilattime,Placenttime,Inducttime,Ripentime,ROMtime,Epiduraltime,Intraantibtime,USdays,LMPdays,onepregflag
MomID,,,,,,,,,,,,,,,,,,,,,
41-00001,41,1.0,3.0,1.0,34.0,4.0,5.0,4.0,1.0,1.0,...,15.0,4.0,361.0,NaN,300.0,343.0,346.0,103.0,271.0,2.0
41-00001,41,1.0,3.0,1.0,36.0,5.0,6.0,5.0,2.0,1.0,...,18.0,3.0,369.0,NaN,251.0,314.0,NaN,128.0,278.0,2.0
41-00002,41,1.0,3.0,1.0,37.0,1.0,3.0,1.0,1.0,1.0,...,NaN,1.0,NaN,NaN,1.0,4.0,NaN,128.0,268.0,1.0
41-00003,41,1.0,3.0,1.0,36.0,1.0,4.0,1.0,1.0,1.0,...,69.0,4.0,382.0,NaN,369.0,364.0,NaN,133.0,273.0,1.0
41-00004,41,1.0,2.0,1.0,34.0,2.0,6.0,2.0,1.0,1.0,...,12.0,5.0,339.0,NaN,105.0,116.0,455.0,204.0,274.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52-07247,52,8.0,1.0,8.0,19.0,0.0,1.0,0.0,9.0,1.0,...,86.0,5.0,1236.0,471.0,464.0,403.0,NaN,NaN,260.0,1.0
52-07248,52,8.0,8.0,8.0,34.0,1.0,3.0,1.0,9.0,2.0,...,NaN,NaN,168.0,1580.0,NaN,182.0,NaN,NaN,175.0,1.0
52-07249,52,8.0,8.0,8.0,28.0,3.0,5.0,2.0,9.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
52-07250,52,8.0,8.0,8.0,16.0,0.0,1.0,0.0,9.0,1.0,...,NaN,5.0,NaN,NaN,NaN,248.0,NaN,NaN,NaN,1.0
52-07251,52,8.0,8.0,8.0,44.0,3.0,7.0,3.0,9.0,1.0,...,4.0,6.0,244.0,NaN,NaN,13.0,NaN,NaN,212.0,1.0

In [5]:
csl_df['Delmode'].value_counts()

1.0    146073
4.0     39577
5.0     26413
2.0     10698
3.0      5677
Name: Delmode, dtype: int64

In [6]:
for col in csl_df:
    icol = col.lower()
    if 'bmi' in icol or 'dbp' in icol:
        print(col)

PreBMI
AdmDBP

In [7]:
csl_df['PreBMI'].describe()

count    151620.000000
mean         25.446826
std           6.250464
min          11.223301
25%          21.096191
50%          23.900034
75%          28.289190
max          77.814592
Name: PreBMI, dtype: float64

In [8]:
csl_df['PreBMI'].head(20)

MomID
41-00001    18.794464
41-00001    19.577567
41-00002    32.613091
41-00003    22.273554
41-00004    30.541004
41-00005    20.850659
41-00006    21.613634
41-00007    23.777067
41-00008    18.399893
41-00009    20.625766
41-00010    21.926875
41-00011    24.202346
41-00012    30.989293
41-00013    22.657516
41-00014    30.785295
41-00015    25.606072
41-00016    25.685334
41-00017    23.493080
41-00018    48.655334
41-00019    31.957708
Name: PreBMI, dtype: float64

In [9]:
%%time
# Version of convert_integer stored in util_mwb - Takes about 7 min.
from util_mwb import convert_integer 
all_types = convert_integer(csl_df)
csl_df.head()

CPU times: user 3min 36s, sys: 3min 37s, total: 7min 14s
Wall time: 7min 14s

,Sitenum,Marital,Education,Insurance,Momage,Parity,Gravidity,Hxlivebirth,Hxmacrosomia,Hxpreterm,...,Fulldilattime,Placenttime,Inducttime,Ripentime,ROMtime,Epiduraltime,Intraantibtime,USdays,LMPdays,onepregflag
MomID,,,,,,,,,,,,,,,,,,,,,
41-00001,41,1,3,1,34,4,5,4,1,1,...,15,4,361,<NA>,300,343,346,103,271,2
41-00001,41,1,3,1,36,5,6,5,2,1,...,18,3,369,<NA>,251,314,<NA>,128,278,2
41-00002,41,1,3,1,37,1,3,1,1,1,...,<NA>,1,<NA>,<NA>,1,4,<NA>,128,268,1
41-00003,41,1,3,1,36,1,4,1,1,1,...,69,4,382,<NA>,369,364,<NA>,133,273,1
41-00004,41,1,2,1,34,2,6,2,1,1,...,12,5,339,<NA>,105,116,455,204,274,1

In [10]:
csl_df['Momage'].value_counts(sort=False)

26    13083
25    12832
24    12828
27    12716
28    12434
29    12412
23    12272
30    11798
22    11740
31    11135
21    10868
32    10220
20     9740
33     9527
34     8846
19     7902
35     7862
36     6692
18     5822
37     5353
38     4266
17     3762
39     3380
40     2507
16     2176
41     1760
42     1251
15      993
43      728
44      397
14      278
45      231
46      117
47       53
13       46
48       31
49       18
50       13
12        8
51        6
52        5
55        2
53        2
11        1
54        1
58        1
Name: Momage, dtype: Int64

# Read "data5"

In [11]:
os.chdir('/MFMDatasets/MFM_bopf/data/csl')
d5 = pd.read_csv('MFM_data5.csv', index_col=0)
d5

,MomID,Sitenum,Momdeath,MomICU,Bloodproduct,Posttransfus,onepregflag,AB_any,AB_ceph,AB_clind,...,myocardio_new1,R_preg,Outcome1,high_BMI,high_Age,transfus_yes,high_EBLoss,high_Gravidity,high_MomLOS,high_height
1,b'41-00002',b'41',1,1,1,1,1,1,1,1,...,1,1,1,0,0,1,0,2,3,2.0
2,b'41-00003',b'41',1,1,1,1,1,1,1,1,...,1,1,1,0,0,1,0,3,2,2.0
3,b'41-00004',b'41',1,1,1,1,1,1,1,1,...,1,1,1,0,0,1,0,4,1,3.0
4,b'41-00005',b'41',1,1,1,2,1,1,1,1,...,1,1,1,0,0,2,0,3,2,2.0
5,b'41-00006',b'41',1,1,1,1,1,1,1,1,...,1,1,1,0,0,1,0,1,2,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185409,b'52-07247',b'52',1,1,1,1,1,1,1,1,...,1,1,3,0,3,1,0,1,2,2.0
185410,b'52-07248',b'52',1,1,1,1,1,1,1,1,...,1,1,3,0,0,1,0,2,2,3.0
185411,b'52-07249',b'52',1,2,2,1,1,1,1,1,...,1,1,3,0,0,2,3,3,3,2.0
185412,b'52-07250',b'52',1,1,1,1,1,1,1,1,...,1,1,5,0,3,1,0,1,2,2.0
185413,b'52-07251',b'52',1,1,1,1,1,1,1,1,...,1,1,3,0,1,1,0,4,3,2.0

In [12]:
for col in d5:
    if d5[col].value_counts().index.size == 1:
        print(f'{col} has only 1 value: NEED to DROP')
        d5.drop(col, inplace=True, axis=1)

onepregflag has only 1 value: NEED to DROP
TTTwin has only 1 value: NEED to DROP
R_preg has only 1 value: NEED to DROP

In [13]:
# Remove extraneous characters from strings; had to use .loc[row, col] to avoid warning
d5.loc[:,'MomID'] = d5['MomID'].str.replace('b','')
d5.loc[:,'MomID'] = d5['MomID'].str.replace("'","")
d5.loc[:,'Sitenum'] = d5['Sitenum'].str.replace('b','')
d5.loc[:,'Sitenum'] = d5['Sitenum'].str.replace("'","")

In [14]:
d5.set_index('MomID', inplace=True)
d5.head()

,Sitenum,Momdeath,MomICU,Bloodproduct,Posttransfus,AB_any,AB_ceph,AB_clind,AB_doxy,AB_eryth,...,iufd9,myocardio_new1,Outcome1,high_BMI,high_Age,transfus_yes,high_EBLoss,high_Gravidity,high_MomLOS,high_height
MomID,,,,,,,,,,,,,,,,,,,,,
41-00002,41,1,1,1,1,1,1,1,1,1,...,0,1,1,0,0,1,0,2,3,2.0
41-00003,41,1,1,1,1,1,1,1,1,1,...,0,1,1,0,0,1,0,3,2,2.0
41-00004,41,1,1,1,1,1,1,1,1,1,...,0,1,1,0,0,1,0,4,1,3.0
41-00005,41,1,1,1,2,1,1,1,1,1,...,0,1,1,0,0,2,0,3,2,2.0
41-00006,41,1,1,1,1,1,1,1,1,1,...,0,1,1,0,0,1,0,1,2,3.0

In [15]:
pd.options.display.float_format = "{:,.2f}".format
del5_df = pd.DataFrame(d5['Delmode'].value_counts(sort=False)).sort_index()
del5_df['pct'] = pd.DataFrame(d5['Delmode'].value_counts(sort=False, normalize=True))*100
del5_df

   Delmode   pct
1   117640 63.45
2     9126  4.92
3     4364  2.35
4    32991 17.79
5    21292 11.48

In [16]:
csl_del5_df = pd.DataFrame(csl_df['Delmode'].value_counts(sort=False)).sort_index()
csl_del5_df['pct'] = pd.DataFrame(csl_df['Delmode'].value_counts(sort=False, normalize=True))*100
csl_del5_df

   Delmode   pct
1   146073 63.94
2    10698  4.68
3     5677  2.49
4    39577 17.33
5    26413 11.56

In [17]:
for col in d5:
    icol = col.lower()
    if 'bmi' in icol or 'dbp' in icol or 'high' in icol:
        print(col)

AdmDBP
high_BMI
high_Age
high_EBLoss
high_Gravidity
high_MomLOS
high_height

In [18]:
#for col in csl:
#    print(f'{col}.value_counts:\n{csl[col].value_counts().to_string()}\n')

In [19]:
d5['high_Age'].value_counts()

0    162006
3     17242
1      5972
2       193
Name: high_Age, dtype: int64

In [20]:
pd.crosstab(index=d5['Inoxy_incrdose'], columns=d5['Sitenum'])

Sitenum,41,42,43,44,45,46,47,48,49,50,51,52
Inoxy_incrdose,,,,,,,,,,,,
1,0,0,0,0,0,0,13434,16088,0,13868,0,0
2,0,5858,9665,0,13246,0,0,0,20086,0,0,0
555,0,0,0,0,0,6913,0,0,4189,0,0,6616
666,42856,0,0,0,0,0,0,0,0,0,16060,0
777,0,0,0,16534,0,0,0,0,0,0,0,0

In [21]:
pd.crosstab(index=d5['Hostype'], columns=d5['Sitenum'])

Sitenum,41,42,43,44,45,46,47,48,49,50,51,52
Hostype,,,,,,,,,,,,
1,0,5858,9665,16534,0,6913,0,16088,3118,0,16060,6616
2,28525,0,0,0,13246,0,13434,0,21157,13868,0,0
3,14331,0,0,0,0,0,0,0,0,0,0,0

In [22]:
merged = d5.merge(csl_df[['Momage','PreBMI']], left_index=True, right_index=True, how='inner')
len(merged)

185413

In [23]:
pd.options.display.max_rows = 50
ages = merged[['Momage', 'high_Age','PreBMI','high_BMI']]
ages

          Momage  high_Age  PreBMI  high_BMI
MomID
41-00002      37         0   32.61         0
41-00003      36         0   22.27         0
41-00004      34         0   30.54         0
41-00005      31         0   20.85         0
41-00006      21         0   21.61         0
...          ...       ...     ...       ...
52-07247      19         3   38.22         0
52-07248      34         0     NaN         0
52-07249      28         0   23.19         0
52-07250      16         3   22.86         0
52-07251      44         1   29.32         0

[185413 rows x 4 columns]

In [24]:
pd.options.display.max_columns = None
pd.crosstab(columns=ages['high_Age'], index=ages['Momage'])

high_Age      0     1   2     3
Momage
11            0     0   0     1
12            0     0   0     8
13            0     0   0    41
14            0     0   0   246
15            0     0   0   849
16            0     0   0  1859
17            0     0   0  3130
18            0     0   0  4758
19            0     0   0  6350
20         7669     0   0     0
21         8539     0   0     0
22         9090     0   0     0
23         9594     0   0     0
24        10093     0   0     0
25        10264     0   0     0
26        10577     0   0     0
27        10325     0   0     0
28        10213     0   0     0
29        10063     0   0     0
30         9693     0   0     0
31         9061     0   0     0
32         8363     0   0     0
33         7796     0   0     0
34         7310     0   0     0
35         6495     0   0     0
36         5590     0   0     0
37         4500     0   0     0
38         3615     0   0     0
39         2911     0   0     0
40            0  2158   0     0
41            0  1512   0     0
42            0  1110   0     0
43            0   641   0     0
44            0   350   0     0
45            0   201   0     0
46            0     0  90     0
47            0     0  44     0
48            0     0  26     0
49            0     0  13     0
50            0     0   7     0
51            0     0   5     0
52            0     0   2     0
53            0     0   2     0
54            0     0   1     0
55            0     0   2     0
58            0     0   1     0

In [25]:
csl_df.loc['52-07250','Momage']

16

In [26]:
ages.groupby("high_Age").count()

          Momage  PreBMI  high_BMI
high_Age
0         161761  110296    162006
1           5972    3984      5972
2            193     121       193
3          17242   11195     17242

In [27]:
ages.groupby(["high_Age","Momage"]).size()

high_Age  Momage
0         20         7669
          21         8539
          22         9090
          23         9594
          24        10093
          25        10264
          26        10577
          27        10325
          28        10213
          29        10063
          30         9693
          31         9061
          32         8363
          33         7796
          34         7310
          35         6495
          36         5590
          37         4500
          38         3615
          39         2911
1         40         2158
          41         1512
          42         1110
          43          641
          44          350
          45          201
2         46           90
          47           44
          48           26
          49           13
          50            7
          51            5
          52            2
          53            2
          54            1
          55            2
          58            1
3         11            1
          12            8
          13           41
          14          246
          15          849
          16         1859
          17         3130
          18         4758
          19         6350
dtype: int64

In [28]:
pd.options.display.max_rows = 200
pd.options.display.min_rows = 20
ct = pd.crosstab(columns=ages['high_BMI'], index=ages['PreBMI'])
ct

high_BMI  0  1  2  3
PreBMI
11.22     0  0  0  1
12.43     0  0  0  1
12.73     0  0  0  1
12.91     0  0  0  1
13.01     0  0  0  1
13.19     0  0  0  1
13.31     0  0  0  1
13.63     0  0  0  1
13.66     0  0  0  1
13.66     0  0  0  1
...      .. .. .. ..
70.71     0  0  1  0
70.81     0  0  1  0
71.36     0  0  1  0
71.99     0  0  1  0
72.33     0  0  1  0
72.47     0  0  1  0
73.19     0  0  1  0
73.97     0  0  1  0
74.88     0  0  1  0
77.81     0  0  1  0

[10938 rows x 4 columns]

In [29]:
ages['Momage'].isna().sum()

245

In [30]:
ages['PreBMI'].isna().sum()

59817

In [23]:
ages['high_BMI'].value_counts(sort=False)

0    161785
3     19325
1      3675
2       628
Name: high_BMI, dtype: int64

In [40]:
ages['pBMI'] = np.floor(ages['PreBMI']).astype('Int8')
ages

/opt/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

          Momage  high_Age     PreBMI  high_BMI  pBMI
MomID
41-00002      37         0  32.613091         0    32
41-00003      36         0  22.273554         0    22
41-00004      34         0  30.541004         0    30
41-00005      31         0  20.850659         0    20
41-00006      21         0  21.613634         0    21
41-00007      42         1  23.777067         0    23
41-00008      33         0  18.399893         3    18
41-00009      34         0  20.625766         0    20
41-00010      33         0  21.926875         0    21
41-00011      23         0  24.202346         0    24
41-00012      28         0  30.989293         0    30
41-00013      22         0  22.657516         0    22
41-00014      39         0  30.785295         0    30
41-00015      31         0  25.606072         0    25
41-00016      31         0  25.685334         0    25
41-00017      35         0  23.493080         0    23
41-00018      36         0  48.655334         1    48
41-00019      24         0  31.957708         0    31
41-00020      28         0  24.694593         0    24
41-00021      27         0  21.522538         0    21
41-00023      33         0  21.216460         0    21
41-00024      38         0  52.126647         2    52
41-00025      40         1  29.287632         0    29
41-00026      40         1  20.526469         0    20
41-00027      33         0  20.674174         0    20
41-00028      32         0        NaN         0  <NA>
41-00029      38         0  20.948604         0    20
41-00030      40         1  29.180134         0    29
41-00031      37         0  19.485426         3    19
41-00032      33         0  18.794464         3    18
41-00033      40         1  38.793711         0    38
41-00037      37         0  41.568210         1    41
41-00038      39         0  20.254446         0    20
41-00039      33         0  35.073766         0    35
41-00040      18         3  24.210385         0    24
41-00041      32         0        NaN         0  <NA>
41-00042      39         0  25.842388         0    25
41-00043      31         0  38.252408         0    38
41-00044      35         0  32.340315         0    32
41-00045      32         0  23.403372         0    23
41-00046      24         0  18.516748         3    18
41-00047      28         0  19.197447         3    19
41-00048      36         0  40.721339         1    40
41-00049      30         0  20.800875         0    20
41-00050      32         0  23.241970         0    23
41-00051      33         0  30.553317         0    30
41-00052      21         0  35.278284         0    35
41-00053      33         0  20.784105         0    20
41-00055      38         0  23.777067         0    23
41-00056      34         0  21.286709         0    21
41-00057      31         0  29.582419         0    29
41-00058      33         0  22.142529         0    22
41-00059      35         0  28.191696         0    28
41-00060      40         1  22.046948         0    22
41-00061      36         0  24.717290         0    24
41-00062      36         0  27.408594         0    27
41-00063      36         0  26.625491         0    26
41-00064      32         0  34.055942         0    34
41-00066      34         0  22.434957         0    22
41-00067      41         1  17.949909         3    17
41-00068      23         0  40.609984         1    40
41-00069      35         0  21.611108         0    21
41-00070      34         0  36.217696         0    36
41-00071      38         0  21.079688         0    21
41-00072      35         0  22.849761         0    22
41-00076      30         0  19.739502         3    19
41-00077      36         0  21.457013         0    21
41-00078      40         1  19.485426         3    19
41-00079      32         0  22.851090         0    22
41-00080      32         0  32.120889         0    32
41-00081      15         3  23.913931         0    23
41-00083      37         0  28.057807         0    28
41-00084      35         0  17.639142         3    17
41-00085      44         1  28.321895         0    28
41-00086      28         0  22.596359         0    22
41-00087      33         0  35.073766         0    35
41-00089      38         0  25.626678         0    25
41-00090      35         0  19.570355         3    19
41-00091      19         3  32.078160         0    32
41-00092      31         0  22.596359         0    22
41-00093      33         0  23.627627         0    23
41-00094      30         0  23.726177         0    23
41-00095      27         0        NaN         0  <NA>
41-00096      39         0  40.337244         1    40
41-00097      24         0  42.287544         1    42
41-00098      31         0  18.023024         3    18
41-00101      25         0  21.005239         0    21
41-00103      34         0  25.747177         0    25
41-00104      34         0  28.532480         0    28
41-00105      36         0  25.990390         0    25
41-00106      32         0  21.627629         0    21
41-00107      37         0  18.794464         3    18
41-00108      31         0  21.079688         0    21
41-00110      40         1  25.060586         0    25
41-00111      26         0  36.022723         0    36
41-00112      35         0  23.332282         0    23
41-00113      29         0  32.107210         0    32
41-00114      28         0  19.739502         3    19
41-00115      33         0  23.726177         0    23
41-00116      34         0  22.434957         0    22
...          ...       ...        ...       ...   ...
52-07150      15         3        NaN         0  <NA>
52-07151      29         0        NaN         0  <NA>
52-07152      23         0        NaN         0  <NA>
52-07153      31         0        NaN         0  <NA>
52-07154      18         3        NaN         0  <NA>
52-07155      18         3        NaN         0  <NA>
52-07156      32         0        NaN         0  <NA>
52-07158      20         0        NaN         0  <NA>
52-07159      25         0        NaN         0  <NA>
52-07160      18         3        NaN         0  <NA>
52-07161      25         0        NaN         0  <NA>
52-07162      28         0        NaN         0  <NA>
52-07163      17         3        NaN         0  <NA>
52-07164      36         0        NaN         0  <NA>
52-07165      38         0        NaN         0  <NA>
52-07166      22         0        NaN         0  <NA>
52-07167      22         0        NaN         0  <NA>
52-07168      30         0        NaN         0  <NA>
52-07169      27         0        NaN         0  <NA>
52-07170      19         3        NaN         0  <NA>
52-07171      20         0        NaN         0  <NA>
52-07172      34         0        NaN         0  <NA>
52-07173      29         0        NaN         0  <NA>
52-07174      36         0        NaN         0  <NA>
52-07175      29         0        NaN         0  <NA>
52-07176      21         0        NaN         0  <NA>
52-07177      31         0        NaN         0  <NA>
52-07178      22         0        NaN         0  <NA>
52-07179      28         0        NaN         0  <NA>
52-07180      27         0        NaN         0  <NA>
52-07181      21         0        NaN         0  <NA>
52-07182      34         0        NaN         0  <NA>
52-07183      19         3        NaN         0  <NA>
52-07184      33         0        NaN         0  <NA>
52-07185      29         0        NaN         0  <NA>
52-07186      33         0        NaN         0  <NA>
52-07187      18         3        NaN         0  <NA>
52-07188      26         0        NaN         0  <NA>
52-07189      22         0        NaN         0  <NA>
52-07190      25         0        NaN         0  <NA>
52-07191      31         0        NaN         0  <NA>
52-07192      26         0        NaN         0  <NA>
52-07193      27         0        NaN         0  <NA>
52-07194      20         0        NaN         0  <NA>
52-07195      25         0        NaN         0  <NA>
52-07196      17         3        NaN         0  <NA>
52-07197      19         3        NaN         0  <NA>
52-07198      30         0        NaN         0  <NA>
52-07199      27         0        NaN         0  <NA>
52-07200      19         3        NaN         0  <NA>
52-07201      34         0        NaN         0  <NA>
52-07202      18         3        NaN         0  <NA>
52-07203      23         0        NaN         0  <NA>
52-07204      34         0        NaN         0  <NA>
52-07205      25         0        NaN         0  <NA>
52-07207      18         3        NaN         0  <NA>
52-07208      30         0        NaN         0  <NA>
52-07209      26         0        NaN         0  <NA>
52-07210      21         0        NaN         0  <NA>
52-07211      26         0        NaN         0  <NA>
52-07212      40         1        NaN         0  <NA>
52-07213      19         3        NaN         0  <NA>
52-07214      22         0        NaN         0  <NA>
52-07215      27         0        NaN         0  <NA>
52-07216      22         0        NaN         0  <NA>
52-07217      24         0        NaN         0  <NA>
52-07218      22         0        NaN         0  <NA>
52-07219      32         0        NaN         0  <NA>
52-07220      16         3        NaN         0  <NA>
52-07221      40         1        NaN         0  <NA>
52-07222      33         0        NaN         0  <NA>
52-07223      16         3        NaN         0  <NA>
52-07224      18         3  22.082032         0    22
52-07225      22         0        NaN         0  <NA>
52-07226      35         0  17.888773         3    17
52-07227      40         1  27.648894         0    27
52-07228      33         0  21.656566         0    21
52-07229      37         0  29.234375         0    29
52-07230      27         0  23.658402         0    23
52-07231      25         0  30.243103         0    30
52-07232      21         0        NaN         0  <NA>
52-07233      27         0        NaN         0  <NA>
52-07234      28         0        NaN         0  <NA>
52-07235      35         0        NaN         0  <NA>
52-07236      29         0        NaN         0  <NA>
52-07237      23         0        NaN         0  <NA>
52-07238      27         0  32.200089         0    32
52-07239      24         0        NaN         0  <NA>
52-07240      26         0  23.331047         0    23
52-07241      28         0        NaN         0  <NA>
52-07242      18         3        NaN         0  <NA>
52-07243      33         0        NaN         0  <NA>
52-07244      29         0  27.595998         0    27
52-07245      29         0        NaN         0  <NA>
52-07246      26         0        NaN         0  <NA>
52-07247      19         3  38.219370         0    38
52-07248      34         0        NaN         0  <NA>
52-07249      28         0  23.185525         0    23
52-07250      16         3  22.855469         0    22
52-07251      44         1  29.322314         0    29

[185413 rows x 5 columns]

In [32]:
pd.options.display.max_rows = 200
pd.options.display.min_rows = 200
pd.crosstab(index=ages['pBMI'], columns=ages['high_BMI'])

high_BMI     0  1   2     3
pBMI
11.2         0  0   0     1
12.4         0  0   0     1
12.7         0  0   0     1
12.9         0  0   0     1
13.0         0  0   0     1
13.2         0  0   0     1
13.3         0  0   0     1
13.6         0  0   0     1
13.7         0  0   0     6
13.8         0  0   0     1
13.9         0  0   0     3
14.1         0  0   0     2
14.2         0  0   0     7
14.3         0  0   0     3
14.4         0  0   0     2
14.5         0  0   0     8
14.6         0  0   0     6
14.7         0  0   0     6
14.8         0  0   0    12
14.9         0  0   0     9
15.0         0  0   0    19
15.1         0  0   0    13
15.2         0  0   0    18
15.3         0  0   0    27
15.4         0  0   0    24
15.5         0  0   0    18
15.6         0  0   0    28
15.7         0  0   0    43
15.8         0  0   0    39
15.9         0  0   0    38
16.0         0  0   0    44
16.1         0  0   0    66
16.2         0  0   0    50
16.3         0  0   0    98
16.4         0  0   0    67
16.5         0  0   0    78
16.6         0  0   0   144
16.7         0  0   0   132
16.8         0  0   0   170
16.9         0  0   0   121
17.0         0  0   0   152
17.1         0  0   0   147
17.2         0  0   0   298
17.3         0  0   0   217
17.4         0  0   0   269
17.5         0  0   0   306
17.6         0  0   0   228
17.7         0  0   0   481
17.8         0  0   0   299
17.9         0  0   0   416
18.0         0  0   0   479
18.1         0  0   0   333
18.2         0  0   0   439
18.3         0  0   0   638
18.4         0  0   0   496
18.5         0  0   0   544
18.6         0  0   0   682
18.7         0  0   0   472
18.8         0  0   0   882
18.9         0  0   0   676
19.0         0  0   0   748
19.1         0  0   0   808
19.2         0  0   0   761
19.3         0  0   0   748
19.4         0  0   0   674
19.5         0  0   0  1216
19.6         0  0   0  1150
19.7         0  0   0   861
19.8         0  0   0   999
19.9         0  0   0   781
20.0       423  0   0   815
20.1      1030  0   0     0
20.2      1158  0   0     0
20.3       755  0   0     0
20.4      1600  0   0     0
20.5      1115  0   0     0
20.6      1053  0   0     0
20.7      1084  0   0     0
20.8      1412  0   0     0
20.9       899  0   0     0
21.0      1373  0   0     0
21.1      1079  0   0     0
21.2       998  0   0     0
21.3      1871  0   0     0
21.4       497  0   0     0
21.5      1393  0   0     0
21.6      1514  0   0     0
21.7      1181  0   0     0
21.8      1027  0   0     0
21.9      1229  0   0     0
22.0      1268  0   0     0
22.1      1472  0   0     0
22.2       949  0   0     0
22.3      1463  0   0     0
22.4       394  0   0     0
22.5      1683  0   0     0
22.6       889  0   0     0
22.7      1355  0   0     0
22.8       987  0   0     0
22.9       727  0   0     0
...        ... ..  ..   ...
55.3         0  0   5     0
55.4         0  0   3     0
55.5         0  0   4     0
55.6         0  0   6     0
55.7         0  0   5     0
55.8         0  0   3     0
55.9         0  0   2     0
56.0         0  0   7     0
56.1         0  0   3     0
56.3         0  0   4     0
56.4         0  0   3     0
56.5         0  0   5     0
56.6         0  0  11     0
56.7         0  0   4     0
56.8         0  0   3     0
57.0         0  0   2     0
57.2         0  0   3     0
57.3         0  0   6     0
57.4         0  0   2     0
57.5         0  0   4     0
57.6         0  0   4     0
57.8         0  0   4     0
57.9         0  0   2     0
58.0         0  0   3     0
58.1         0  0   6     0
58.2         0  0   3     0
58.3         0  0   4     0
58.4         0  0   3     0
58.5         0  0   5     0
58.6         0  0   1     0
58.9         0  0   3     0
59.0         0  0   3     0
59.1         0  0   1     0
59.2         0  0   2     0
59.3         0  0   1     0
59.5         0  0   2     0
59.6         0  0   2     0
59.7         0  0   3     0
59.8         0  0   2     0
60.0         0  0   2     0
60.1         0  0   2     0
60.2         0  0   2     0
60.3         0  0   1     0
60.4         0  0   3     0
60.5         0  0   5     0
60.6         0  0   3     0
60.7         0  0   1     0
60.8         0  0   2     0
61.0         0  0   1     0
61.1         0  0   1     0
61.2         0  0   2     0
61.5         0  0   2     0
61.7         0  0   2     0
61.8         0  0   1     0
61.9         0  0   1     0
62.0         0  0   3     0
62.1         0  0   3     0
62.4         0  0   1     0
62.5         0  0   2     0
62.6         0  0   2     0
62.7         0  0   2     0
62.8         0  0   1     0
63.0         0  0   1     0
63.3         0  0   1     0
63.4         0  0   1     0
63.5         0  0   1     0
63.7         0  0   1     0
63.8         0  0   1     0
64.0         0  0   1     0
64.5         0  0   1     0
64.6         0  0   1     0
64.7         0  0   1     0
64.9         0  0   1     0
65.2         0  0   1     0
65.3         0  0   1     0
65.8         0  0   2     0
65.9         0  0   1     0
66.1         0  0   1     0
66.3         0  0   1     0
66.5         0  0   1     0
66.7         0  0   1     0
66.8         0  0   1     0
67.0         0  0   1     0
67.2         0  0   2     0
67.5         0  0   1     0
67.6         0  0   2     0
67.8         0  0   1     0
68.7         0  0   1     0
68.9         0  0   1     0
69.9         0  0   2     0
70.7         0  0   1     0
70.8         0  0   1     0
71.4         0  0   1     0
72.0         0  0   1     0
72.3         0  0   1     0
72.5         0  0   1     0
73.2         0  0   1     0
74.0         0  0   1     0
74.9         0  0   1     0
77.8         0  0   1     0

[523 rows x 4 columns]

In [44]:
ages[(ages['PreBMI'].isna())]

          Momage  high_Age  PreBMI  high_BMI  pBMI
MomID
41-00028      32         0     NaN         0  <NA>
41-00041      32         0     NaN         0  <NA>
41-00095      27         0     NaN         0  <NA>
41-00138      36         0     NaN         0  <NA>
41-00148      25         0     NaN         0  <NA>
41-00169      47         2     NaN         0  <NA>
41-00237      31         0     NaN         0  <NA>
41-00307      17         3     NaN         0  <NA>
41-00335      32         0     NaN         0  <NA>
41-00387      27         0     NaN         0  <NA>
41-00392      31         0     NaN         0  <NA>
41-00398      34         0     NaN         0  <NA>
41-00453      25         0     NaN         0  <NA>
41-00489      20         0     NaN         0  <NA>
41-00503      32         0     NaN         0  <NA>
41-00543      31         0     NaN         0  <NA>
41-00544      30         0     NaN         0  <NA>
41-00556      25         0     NaN         0  <NA>
41-00893      35         0     NaN         0  <NA>
41-00922      34         0     NaN         0  <NA>
41-01021      27         0     NaN         0  <NA>
41-01064      21         0     NaN         0  <NA>
41-01110      24         0     NaN         0  <NA>
41-01206      21         0     NaN         0  <NA>
41-01215      24         0     NaN         0  <NA>
41-01285      24         0     NaN         0  <NA>
41-01429      31         0     NaN         0  <NA>
41-01467      28         0     NaN         0  <NA>
41-01489      24         0     NaN         0  <NA>
41-01578      27         0     NaN         0  <NA>
41-01760      34         0     NaN         0  <NA>
41-01773      27         0     NaN         0  <NA>
41-01815      36         0     NaN         0  <NA>
41-02035      22         0     NaN         0  <NA>
41-02163      22         0     NaN         0  <NA>
41-02173      20         0     NaN         0  <NA>
41-02200      29         0     NaN         0  <NA>
41-02222      33         0     NaN         0  <NA>
41-02267      22         0     NaN         0  <NA>
41-02274      24         0     NaN         0  <NA>
41-02300      30         0     NaN         0  <NA>
41-02309      20         0     NaN         0  <NA>
41-02316      33         0     NaN         0  <NA>
41-02323      24         0     NaN         0  <NA>
41-02330      25         0     NaN         0  <NA>
41-02352      26         0     NaN         0  <NA>
41-02510      29         0     NaN         0  <NA>
41-02515      26         0     NaN         0  <NA>
41-02528      23         0     NaN         0  <NA>
41-02608      20         0     NaN         0  <NA>
41-02613      19         3     NaN         0  <NA>
41-02627      20         0     NaN         0  <NA>
41-02744      25         0     NaN         0  <NA>
41-02787      27         0     NaN         0  <NA>
41-02792      31         0     NaN         0  <NA>
41-02837      23         0     NaN         0  <NA>
41-02910      31         0     NaN         0  <NA>
41-03028      35         0     NaN         0  <NA>
41-03086      30         0     NaN         0  <NA>
41-03131      31         0     NaN         0  <NA>
41-03257      25         0     NaN         0  <NA>
41-03296      24         0     NaN         0  <NA>
41-03326      26         0     NaN         0  <NA>
41-03363      30         0     NaN         0  <NA>
41-03408      22         0     NaN         0  <NA>
41-03413      22         0     NaN         0  <NA>
41-03415      30         0     NaN         0  <NA>
41-03485      24         0     NaN         0  <NA>
41-03497      24         0     NaN         0  <NA>
41-03530      27         0     NaN         0  <NA>
41-03602      21         0     NaN         0  <NA>
41-03619      21         0     NaN         0  <NA>
41-03765      30         0     NaN         0  <NA>
41-03797      41         1     NaN         0  <NA>
41-03849      29         0     NaN         0  <NA>
41-03901      43         1     NaN         0  <NA>
41-03977      34         0     NaN         0  <NA>
41-04010      34         0     NaN         0  <NA>
41-04031      26         0     NaN         0  <NA>
41-04034      36         0     NaN         0  <NA>
41-04038      42         1     NaN         0  <NA>
41-04058      30         0     NaN         0  <NA>
41-04087      31         0     NaN         0  <NA>
41-04103      31         0     NaN         0  <NA>
41-04114      33         0     NaN         0  <NA>
41-04205      27         0     NaN         0  <NA>
41-04406      24         0     NaN         0  <NA>
41-04447      28         0     NaN         0  <NA>
41-04452      27         0     NaN         0  <NA>
41-04465      28         0     NaN         0  <NA>
41-04489      23         0     NaN         0  <NA>
41-04492      23         0     NaN         0  <NA>
41-04545      25         0     NaN         0  <NA>
41-04578      24         0     NaN         0  <NA>
41-04581      25         0     NaN         0  <NA>
41-04605      20         0     NaN         0  <NA>
41-04638      22         0     NaN         0  <NA>
41-04643      24         0     NaN         0  <NA>
41-04679      22         0     NaN         0  <NA>
41-04781      28         0     NaN         0  <NA>
...          ...       ...     ...       ...   ...
52-07136      31         0     NaN         0  <NA>
52-07137      32         0     NaN         0  <NA>
52-07138      27         0     NaN         0  <NA>
52-07139      20         0     NaN         0  <NA>
52-07140      21         0     NaN         0  <NA>
52-07141      27         0     NaN         0  <NA>
52-07142      18         3     NaN         0  <NA>
52-07143      28         0     NaN         0  <NA>
52-07144      27         0     NaN         0  <NA>
52-07145      25         0     NaN         0  <NA>
52-07146      22         0     NaN         0  <NA>
52-07147      28         0     NaN         0  <NA>
52-07148      20         0     NaN         0  <NA>
52-07149      26         0     NaN         0  <NA>
52-07150      15         3     NaN         0  <NA>
52-07151      29         0     NaN         0  <NA>
52-07152      23         0     NaN         0  <NA>
52-07153      31         0     NaN         0  <NA>
52-07154      18         3     NaN         0  <NA>
52-07155      18         3     NaN         0  <NA>
52-07156      32         0     NaN         0  <NA>
52-07158      20         0     NaN         0  <NA>
52-07159      25         0     NaN         0  <NA>
52-07160      18         3     NaN         0  <NA>
52-07161      25         0     NaN         0  <NA>
52-07162      28         0     NaN         0  <NA>
52-07163      17         3     NaN         0  <NA>
52-07164      36         0     NaN         0  <NA>
52-07165      38         0     NaN         0  <NA>
52-07166      22         0     NaN         0  <NA>
52-07167      22         0     NaN         0  <NA>
52-07168      30         0     NaN         0  <NA>
52-07169      27         0     NaN         0  <NA>
52-07170      19         3     NaN         0  <NA>
52-07171      20         0     NaN         0  <NA>
52-07172      34         0     NaN         0  <NA>
52-07173      29         0     NaN         0  <NA>
52-07174      36         0     NaN         0  <NA>
52-07175      29         0     NaN         0  <NA>
52-07176      21         0     NaN         0  <NA>
52-07177      31         0     NaN         0  <NA>
52-07178      22         0     NaN         0  <NA>
52-07179      28         0     NaN         0  <NA>
52-07180      27         0     NaN         0  <NA>
52-07181      21         0     NaN         0  <NA>
52-07182      34         0     NaN         0  <NA>
52-07183      19         3     NaN         0  <NA>
52-07184      33         0     NaN         0  <NA>
52-07185      29         0     NaN         0  <NA>
52-07186      33         0     NaN         0  <NA>
52-07187      18         3     NaN         0  <NA>
52-07188      26         0     NaN         0  <NA>
52-07189      22         0     NaN         0  <NA>
52-07190      25         0     NaN         0  <NA>
52-07191      31         0     NaN         0  <NA>
52-07192      26         0     NaN         0  <NA>
52-07193      27         0     NaN         0  <NA>
52-07194      20         0     NaN         0  <NA>
52-07195      25         0     NaN         0  <NA>
52-07196      17         3     NaN         0  <NA>
52-07197      19         3     NaN         0  <NA>
52-07198      30         0     NaN         0  <NA>
52-07199      27         0     NaN         0  <NA>
52-07200      19         3     NaN         0  <NA>
52-07201      34         0     NaN         0  <NA>
52-07202      18         3     NaN         0  <NA>
52-07203      23         0     NaN         0  <NA>
52-07204      34         0     NaN         0  <NA>
52-07205      25         0     NaN         0  <NA>
52-07207      18         3     NaN         0  <NA>
52-07208      30         0     NaN         0  <NA>
52-07209      26         0     NaN         0  <NA>
52-07210      21         0     NaN         0  <NA>
52-07211      26         0     NaN         0  <NA>
52-07212      40         1     NaN         0  <NA>
52-07213      19         3     NaN         0  <NA>
52-07214      22         0     NaN         0  <NA>
52-07215      27         0     NaN         0  <NA>
52-07216      22         0     NaN         0  <NA>
52-07217      24         0     NaN         0  <NA>
52-07218      22         0     NaN         0  <NA>
52-07219      32         0     NaN         0  <NA>
52-07220      16         3     NaN         0  <NA>
52-07221      40         1     NaN         0  <NA>
52-07222      33         0     NaN         0  <NA>
52-07223      16         3     NaN         0  <NA>
52-07225      22         0     NaN         0  <NA>
52-07232      21         0     NaN         0  <NA>
52-07233      27         0     NaN         0  <NA>
52-07234      28         0     NaN         0  <NA>
52-07235      35         0     NaN         0  <NA>
52-07236      29         0     NaN         0  <NA>
52-07237      23         0     NaN         0  <NA>
52-07239      24         0     NaN         0  <NA>
52-07241      28         0     NaN         0  <NA>
52-07242      18         3     NaN         0  <NA>
52-07243      33         0     NaN         0  <NA>
52-07245      29         0     NaN         0  <NA>
52-07246      26         0     NaN         0  <NA>
52-07248      34         0     NaN         0  <NA>

[59817 rows x 5 columns]